apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    name: test
spec:
  ports:
    - port: 5003
  selector:
    name: test
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
        - name: test
          image: brecheisen/test:v1
          ports:
            - containerPort: 5003
  selector:
    matchLabels:
      name: test