apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    name: storage
spec:
  ports:
    - port: 80
  selector:
    name: storage
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: storage
    spec:
      containers:
        - name: nginx
          image: brecheisen/storage-nginx:v1
          ports:
            - containerPort: 80
        - name: storage
          image: brecheisen/storage:v1
  selector:
    matchLabels:
      name: storage