apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-volume
  labels:
    name: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    # HostPath volumes are only accesible on a single node, i.e., ReadWriteOnce.
  - ReadWriteOnce
  hostPath:
    path: /tmp/files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-volume-claim
  labels:
    name: storage
spec:
  accessModes:
  # Even though the volume may support ReadWriteMany, the claim may expose it
  # only as ReadWriteOnce.
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    name: storage
spec:
  ports:
    - port: 80
  selector:
    name: storage
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: storage
    spec:
      containers:
        - name: ngx
          image: brecheisen/storage-ngx:v1
          ports:
            - containerPort: 80
          # Before stopping the pod, make sure Nginx gracefully terminates by
          # finishing ongoing requests.
          lifecycle:
            preStop:
              exec:
                command: ["/usr/local/sbin/nginx", "-s", "quit"]
          volumeMounts:
          - name: files
            mountPath: /mnt/shared/files
        - name: storage
          image: brecheisen/storage:v1
          volumeMounts:
          - name: files
            mountPath: /mnt/shared/files
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: files-volume-claim
  selector:
    matchLabels:
      name: storage