apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    name: auth
spec:
  ports:
    - port: 5000
  selector:
    name: auth
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: auth
          image: brecheisen/auth:v1
          ports:
            - containerPort: 5000
          command: ["./run.sh"]
  selector:
    matchLabels:
      name: auth